# Generated by Django 2.2.10 on 2021-08-31 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerForChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Ответ_на_выбор',
            },
        ),
        migrations.CreateModel(
            name='UserChoiceAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(null=True, verbose_name='UserId')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.AnswerForChoice', verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Выбранный_вариант',
            },
        ),
        migrations.RemoveField(
            model_name='answertext',
            name='question',
        ),
        migrations.DeleteModel(
            name='UserID',
        ),
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ('-start_date',), 'verbose_name': 'Опрос'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('id',), 'verbose_name': 'Вопрос'},
        ),
        migrations.RemoveField(
            model_name='question',
            name='polls',
        ),
        migrations.AddField(
            model_name='question',
            name='poll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Poll', verbose_name='Опрос_мастер'),
        ),
        migrations.AddField(
            model_name='question',
            name='type_question',
            field=models.CharField(choices=[('ONE', 'ONE'), ('MULT', 'MULT'), ('TEXT', 'TEXT')], default='ONE', max_length=4, verbose_name='Тип_вопроса'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='end_date',
            field=models.DateField(verbose_name='Дата_окончания'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='start_date',
            field=models.DateField(auto_now_add=True, db_index=True, verbose_name='Дата_начала'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text_question',
            field=models.TextField(verbose_name='Текст_вопроса'),
        ),
        migrations.DeleteModel(
            name='AnswerText',
        ),
        migrations.AddField(
            model_name='userchoiceanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question', verbose_name='МастерВопрос'),
        ),
        migrations.AddField(
            model_name='answerforchoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question', verbose_name='МастерВопрос'),
        ),
    ]
